# Generated by Django 2.1 on 2019-12-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20191208_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='amount',
            field=models.PositiveIntegerField(default=1, verbose_name='수량'),
        ),
    ]
