# Generated by Django 2.1 on 2019-12-13 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_orderproduct_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertransaction',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
