# Generated by Django 2.1 on 2019-12-15 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_ordertransaction_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.PositiveIntegerField(default=0, verbose_name='전체 수량'),
        ),
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.PositiveIntegerField(default=0, verbose_name='전체 가격'),
        ),
    ]
