# Generated by Django 2.1 on 2019-12-15 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20191215_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertransaction',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
