# Generated by Django 2.1 on 2019-12-16 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20191215_2335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordertransaction',
            name='transaction_id',
        ),
    ]
