# Generated by Django 2.1 on 2019-12-16 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_remove_ordertransaction_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.BooleanField(default=False, verbose_name='결제 검증 상태'),
        ),
        migrations.AlterField(
            model_name='ordertransaction',
            name='status',
            field=models.BooleanField(default=False, verbose_name='결제 상태'),
        ),
    ]
