# Generated by Django 2.1 on 2019-12-18 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20191217_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertransaction',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrderTransaction', to='order.Order'),
        ),
    ]
